### ISSUE TITLE
pre-launch todo

### ISSUE THREAD

**Issue by ema-fox** [sparkboard/sparkboard#135]
Has to be done before launch
- [ ] email notifications
  - [x] select email provider 
    - AWS SES
- [ ] email & password based login
  - [ ] password recovery
- [x] users can join boards
  - "provisional membership" aka invitation aka application - an entity which tracks a not-yet membership. Then the form can be a "normal" persisted form. 
    - when profile fields are marked as "required", then these are shown on the "joining" page and persisted to the "not-yet-membership"
    - joining a board also means accepting terms for that board. default terms are basically "admins can see your email" but admins should also be able to add their own terms. 
- [x] after-login redirect
- [x] logout
- [x] admins can remove users from boards, projects, and orgs
- [x] admins can appoint new admins
- [ ] plan for manual DB hot fixes
  - ability to REPL into the live server
- [ ] domain names. in scope is ability to set the domain name, have the server configured with a wildcard DNS record to be able to redirect `foo.sparkboard.app` to `sparkboard.app/board/$foo`. This should be simpler than fully hosting each board/org on its own subdomain while retaining the existing convenience / identity experience.
- admins can invite users to entities. when an entity is marked as `invite-only` this is the only way for a person to join. This is also the only way for admins to be added to an org because there's never a way for a user to join an org on their own.
  - [x] boards
  - [x] projects
  - [x] notes
  - [x] orgs

----
- [x] users can join sticky notes
  - fully re-use the membership code from projects. 
  - the "invite only" mode would have the effect of not allowing people to join
  - if the team is empty & mode is "invite only", hide the team section completely
- [ ] data collection when applying / joining:
  - profile fields (possibly required) that are marked as "show at registration"
  - application fields (possibly required) only visible to the user + admins. EXAMPLE: `t-shirt-size`, `meal-preference`, `special-requests`, etc.
    - approach 1 (probably preferred): fields in `:entity/field-entries` have a new field, `:field/show-on-profile?`, which determines whether they are shown on the profile vs only visible to the user and admins. The will add a small amount of overhead/complexity to queries because we will need to filter fields for profile based on who is viewing. Consider renaming the field to `:membership/field-entries` to ensure that we apply filtering at all usage sites. 
    - approach 2: some new attribute, `:membership/application-fields` to store attributes which are conceptually part of the "application" not the "profile". If we did not use a generic attribute like `:entity/field-entries` then we could imagine `:membership/profile-fields` and `:membership/application-fields`. (Keeping in mind that some profile-fields can be marked to be included in the application form). Unsure of the extent to which we rely on `:entity/field-entries` being a generic attribute to handle field entries.

----

Won't be done before launch:
- people can request to join
  - [ ] boards
  - [ ] projects
  - [ ] notes
- the applying/joining flow may be similar for projects, where a board is set up to require that members "propose" or "apply to join" with a project and it requires approval first.
- slack integration
- moderation features
  - admin can "block"/"deactivate" a membership
    - membership still exists, the account cannot simply re-join to create a new membership
    - membership can be re-activated by an admin 
    - the user cannot do anything which normally requires a membership (ie. the authorization code relevant to "must be a member" should check for the flag) - if the board is private, the user can't see it, the user can't post, etc.
- excision: cron job every day, excise entities marked as "deleted_at" which are >= 7 days old

---- 

Idea - create a sparkboard to showcase sparkboard v2's new features. eg:
- create a "project" for each feature, include a description (text field) and images / videos 
- we can all comment on the projects to share feedback (& test how notifications etc work)

possible nav refactor: `nav!` can accept multiple vectors, to set multiple "routers" in one time step.

----
